### PR TITLE
Ingress notation for API Version v1

### PR DESCRIPTION
**Pull request by argo1984**
#### What this PR does / why we need it:
API v1 has another notation for ingress

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[pgadmin4]`)

### CODE REVIEW

**Comment by rowanruseler** [comment]
it seems you are correct, however this implementation would break `networking.k8s.io/v1beta1`.

Is `networking.k8s.io/v1` currently breaking on this? If so, an if else statement should be implemented within `template/ingress.yaml` to switch between the two different styles of defining the port.

**Comment by theminecoder** [comment]
> Is networking.k8s.io/v1 currently breaking on this?

Correct, it is. Currently to install the chart on 1.19+ we are forced to downgrade the chart version back to 1.5.6 to use the v1beta1 version.

**Review by vutny — COMMENTED** [review]
I guess this PR is based on changes which were already reverted.

**Comment by argo1984** [comment]
yes it is. i use in other helm charts for api version v1 instead of v1beta1

**Comment by rowanruseler** [comment]
@argo1984 I am fine with making an adjustment to the helm chart, but the implementation another person did was not fully tested. And was missing a few key points.

So I rolled back to what `helm` itself has currently defined as default. Once helm itself makes the adjustment I can just copy it over.

Maybe I'll have the time next week to otherwise look at it, but feel free to create a correct PR with taking in scope previous versions. Not everybody runs the latest kubernetes version.

**Pull request closed without merging**
