### PR TITLE
[pgadmin4] Deploy latest available pgAdmin version 4.20

### PR DESCRIPTION
**Pull request by vutny**
#### What this PR does / why we need it:
Use current latest released app by default.

#### Checklist
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by rowanruseler** [comment]
@vutny when I did this, it failed to start up. You got it to run? Cause then it seems like an issue on my environment.

**Comment by vutny** [comment]
Thanks for a quick look, @rowanruseler !
CI tests seem to be passed for latest commit.
The tag needs to be a string (explicitly double-quoted), otherwise it is interpreted as a floating number,
i.e. `4.20` :arrow_right: `4.2`.
I've fixed that.

**Comment by rowanruseler** [comment]
@vutny I'll test it tomorrow, already planned to see if it functioned with 4.20 and do some tests.

**Comment by rowanruseler** [comment]
@vutny awesome, worked - not sure if it was my environment previously. But glad it works. Thank you for the pr.

**Comment by vutny** [comment]
Thanks for speedy merge!

**Pull request merged**
