### PR TITLE
fix(pgadmin4): helm install usage

### PR DESCRIPTION
**Pull request by aslafy-z**
#### What this PR does / why we need it:

Fixes some helm commands in the README.

### CODE REVIEW

**Review by vutny — CHANGES_REQUESTED** [review]
That old syntax with `--name` parameter works for Helm 2.x releases. In Helm v3 it is not supported anymore.
But Helm v2 is still maintained and widely used, I believe. You may just change the README to mentioned old and new installation command variant for corresponding Helm versions.

**Comment by aslafy-z** [comment]
You're right! Sorry for that. Updated the README with Helm 2 / 3 variants.

**Comment by rowanruseler** [comment]
@aslafy-z please also bump the chart version if you make an adjustment.

**Comment by aslafy-z** [comment]
I thought it was not needed as I only touch the README. But for sure, will do.

**Review by vutny — APPROVED** [review]
Looks good, thanks!

**Review by rowanruseler — APPROVED** [review]

**Pull request merged**
