### PR TITLE
[pgadmin4] Clean up test pod after running helm test

### PR DESCRIPTION
**Pull request by faraonc**
#### What this PR does / why we need it:
We don't need the pod to be hanging out and introducing noises in the cluster. If it fails, then retain the pod else delete the pod on a successful completion.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

**n/a**

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] ~~Variables are documented in the README.md~~
- [x] Title of the PR starts with chart name (e.g. `[pgadmin4]`)

### CODE REVIEW

**Comment by faraonc** [comment]
It might be better to wait until this [issue](https://github.com/helm/helm/issues/9098) is resolved in helm.

**Review by vutny — COMMENTED** [review]
Looks OK, but requires rebase over the latest master revision.

**Comment by rowanruseler** [comment]
The helm issue is still ongoing, I've been waiting for that to get resolved as the PRer requested.

**Comment by rowanruseler** [comment]
@faraonc could you merge Master into this branch, so it has all the latest testing adjustments?

**Comment by faraonc** [comment]
> @faraonc could you merge Master into this branch, so it has all the latest testing adjustments?

I just saw the email. I just made the update.

**Comment by rowanruseler** [comment]
@faraonc ah so sorry, can you bump the chart version - so we can get this merged?

**Comment by faraonc** [comment]
> @faraonc ah so sorry, can you bump the chart version - so we can get this merged?

Done

**Pull request merged**
