### PR TITLE
[pgadmin4] Add support for custom environment variables

### LINKED ISSUE #9: [pgadmin4] Additional env variables setup
Hi,

It would be nice if we could have a better control of env variables. Currently, few options have explicit configuration, but for each new option we have to crete a new helm value, which is tiresome. Right now, I'd like to set two additional env vars:

```
            - name: PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD
              value: 'False'
            - name: PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED
              value: 'False'
```

and I'd either have to create two additional HELM options, or  extend usage of "values.env" with to generate the block similar to ingress.hosts. See also

https://github.com/helm/charts/blob/f2fcadaa5a1af57bbdf2e49a99f25c9589d5b540/stable/fluentd/templates/deployment.yaml#L68-L71

### PR DESCRIPTION
**Pull request by miro-grapeup**
#### What this PR does / why we need it:
Adds support fot cusom environment variables in pgadmin deployment.

#### Which issue this PR fixes
  - fixes #9 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by rowanruseler** [comment]
@miro-grapeup looks good, but could you please sign your commit? Thank you

**Comment by miro-grapeup** [comment]
If this was simply check the tickmark, then it is done! 👍

**Comment by rowanruseler** [comment]
@miro-grapeup it is not as simple as the check the tickmark, you can easily do it by commit with the option `-s`.

**Comment by rowanruseler** [comment]
@miro-grapeup perhaps you have the time today to resolve the last request?

**Comment by miro-grapeup** [comment]
@rowanruseler I have added the sign-off  and force pushed the commits again

**Comment by rowanruseler** [comment]
@miro-grapeup awesome, just bump the chart version and we good to merge. Thank you for the pull-request.

**Pull request merged**
